---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp hakkimizda.php $DEPLOYPATH
    - /bin/cp iletisim.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
